### ISSUE TITLE
Question about SMARTS code

### ISSUE THREAD

**Issue by drmeister** [lpwgroup/forcebalance-qcarchive#15]

**Comment by drmeister** [comment]
I'm implementing code to assign force-field parameters using the sage force field, and my SMARTS parser is having trouble with one small subexpression in three of the sage parameters.

Where it comes up is in:
https://github.com/openforcefield/openff-forcefields/blob/main/openforcefields/offxml/openff-2.0.0.offxml#L198
Specifically - parameters t56, t57, and i6

The `*@1-[*]=,:[*][*]=,:[*]@1` subexpression and specifically the `@1` subexpression.
The Daylight Theory Manual https://www.daylight.com/dayhtml/doc/theory/index.pdf and the  documentation on the web 
and the SMARTS description here... https://www.daylight.com/dayhtml/doc/theory/theory.smarts.html
describe `@` as the "any ring bond" "Bond Primitive" - but the `@` appears before a number/label that should follow an atomic primitive.   It looks like the `*@1` and `[*]@1` is malformed SMARTS code - yet it works in your code.  

I read in the release notes that this pattern matches a 5-member ring, but so would `*1-[*]=,:[*][*]=,:[*]1`, and so why the extra `@`?

**Comment by j-wags** [comment]
Thanks for writing in @drmeister. I'm not sure that `*@1` is invalid, though I'm having trouble getting a clear resolution from the daylight spec.

One thing I've seen is when a ring-closing bond is non-single, the bond order is indicated by putting the bond decorator before the ring-closure digit. So, for example, benzene could be written as `C1=CC=CC=C1` or `C1C=CC=CC=1`. So far I can tell that this works in RDKit and OpenEye, but I'm still looking for a description/example of this in the daylight docs.

**Comment by j-wags** [comment]
The "bond decorator before ring closure digit" does seem to be explicitly allowed in the [OpenSMILES spec](http://opensmiles.org/opensmiles.html), in section 3.4.

**Comment by drmeister** [comment]
Yes, it does.   I now understand what the ring-closure digit means.  I have always interpreted it as an "atom label" - it's not - it is an "incomplete bond label."  These are subtly different.

Thank you for your feedback and the link to the OpenSmiles specification.
I had been reading the older SMILES and SMARTS specification documents, and they are not as clear on this point.

I now understand what this SMARTS syntax means, and we can close this issue.

**Comment by drmeister** [comment]
One last comment.  I have implemented a partial fix to my code, and I'm working on a complete fix.
I can read the latest Sage force field and assign force-field parameters.
I am building structures like these...
https://usercontent.irccloud-cdn.com/file/Tah5XpYX/image.png

**Comment by j-wags** [comment]
That's great to hear. Thanks for following up!
